/*
 * SofaBuffers C# - tolerance tests: non-canonical but well-formed input decodes
 * to the value it denotes and re-encodes canonically (CORELIB_PLAN §7 item 5b).
 *
 * §4.1 splits the varint rule in two: an ENCODER must emit the minimal form, but
 * a DECODER "MUST accept a non-minimal varint that stays within the 64-bit bound,
 * decode it to the value it denotes, and -- because every re-encode is canonical
 * -- emit the minimal form on any re-encode". The rule "applies wherever a varint
 * appears: field headers, fixlen_words, array element counts, element values".
 * §4.9 adds the sequence-end twin: an end marker whose id sub-field is non-zero
 * (but within ID_MAX) is an ordinary sequence end, and re-encodes as 0x07.
 *
 * These are the cases where an implementation can be too STRICT, which is the one
 * class of divergence a majority-vote conformance check cannot catch (§7 item 5b):
 * every port may reject them uniformly and still agree with itself. The malformed
 * mirror of this file is DecoderErrorsTests; the positive vectors do not cover it
 * because the shared vectors are generated by a canonical encoder and so carry
 * only minimal encodings.
 *
 * SPDX-License-Identifier: MIT
 */

using System.Collections.Generic;
using SofaBuffers.Tests.Common;
using Xunit;
using static SofaBuffers.Tests.Common.TestBytes;

namespace SofaBuffers.Tests;

public class WireToleranceTests
{
    private static List<string> Decode(byte[] wire)
    {
        var visitor = new RecordingVisitor();
        Assert.Equal(DecodeStatus.Complete, new IStream().Feed(wire, visitor));
        return visitor.Events;
    }

    /// <summary>Feed one byte per call, so the byte-at-a-time machine reads the varints.</summary>
    private static List<string> DecodeByteAtATime(byte[] wire)
    {
        var visitor = new RecordingVisitor();
        var iss = new IStream();
        DecodeStatus status = DecodeStatus.Complete;
        foreach (byte b in wire)
        {
            status = iss.Feed(new[] { b }, visitor);
        }
        Assert.Equal(DecodeStatus.Complete, status);
        return visitor.Events;
    }

    [Fact]
    public void NonMinimalFieldHeaderAccepted()
    {
        // 0x88 0x00 is a two-byte spelling of the header 0x08 (id 1, unsigned),
        // and 0x85 0x00 a two-byte spelling of the value 5.
        var expected = new[] { "u:1=5" };
        Assert.Equal(expected, Decode(Bytes(0x88, 0x00, 0x05)));
        Assert.Equal(expected, Decode(Bytes(0x08, 0x85, 0x00)));
        Assert.Equal(expected, Decode(Bytes(0x88, 0x00, 0x85, 0x00)));
        Assert.Equal(expected, DecodeByteAtATime(Bytes(0x88, 0x00, 0x85, 0x00)));

        // ... and a re-encode is canonical again: three minimal bytes, not four.
        Assert.Equal(Bytes(0x08, 0x05), Encode(os => os.WriteUnsigned(1, 5)));
    }

    [Fact]
    public void NonMinimalScalarFixlenWordAccepted()
    {
        // fixlen field id 1; the word (2 << 3) | STRING = 0x12 spelled in two bytes.
        Assert.Equal(new[] { "str:1=hi" }, Decode(Bytes(0x0A, 0x92, 0x00, 0x68, 0x69)));
        Assert.Equal(new[] { "str:1=hi" }, DecodeByteAtATime(Bytes(0x0A, 0x92, 0x00, 0x68, 0x69)));
        Assert.Equal(Bytes(0x0A, 0x12, 0x68, 0x69), Encode(os => os.WriteString(1, "hi")));
    }

    [Fact]
    public void NonMinimalArrayCountAccepted()
    {
        // Integer array id 1 (wire type 3), count 2 spelled as 0x82 0x00.
        Assert.Equal(
            new[] { "arr:1:UNSIGNED:2", "u:1=7", "u:1=9" },
            Decode(Bytes(0x0B, 0x82, 0x00, 0x07, 0x09)));
        Assert.Equal(
            new[] { "arr:1:UNSIGNED:2", "u:1=7", "u:1=9" },
            DecodeByteAtATime(Bytes(0x0B, 0x82, 0x00, 0x07, 0x09)));
    }

    [Fact]
    public void NonMinimalFixlenArrayWordAccepted()
    {
        // A fixlen array's fixlen_word is the third varint of the field (§4.8), and
        // is the one position where a non-minimal spelling is the ONLY way to reach
        // a multi-byte word at all: the word is (4 << 3) | FP32 = 0x20 or
        // (8 << 3) | FP64 = 0x41, both single-byte in minimal form. 0xA0 0x00 is
        // 0x20 in two bytes.
        //
        // One element: only six bytes follow the count, so the word is read by the
        // decoder's short-tail reader.
        Assert.Equal(
            new[] { "arr:1:FP32:1", "f32:1=1" },
            Decode(Bytes(0x0D, 0x01, 0xA0, 0x00, 0x00, 0x00, 0x80, 0x3F)));

        // Three elements: fourteen bytes follow the count, so the same word is read
        // by the eight-bytes-at-a-time reader instead -- a different code path for
        // the identical wire question.
        Assert.Equal(
            new[] { "arr:1:FP32:3", "f32:1=1", "f32:1=2", "f32:1=4" },
            Decode(Bytes(
                0x0D, 0x03, 0xA0, 0x00,
                0x00, 0x00, 0x80, 0x3F,
                0x00, 0x00, 0x00, 0x40,
                0x00, 0x00, 0x80, 0x40)));

        // And byte-at-a-time, which reads the word through the state machine.
        Assert.Equal(
            new[] { "arr:1:FP32:1", "f32:1=1" },
            DecodeByteAtATime(Bytes(0x0D, 0x01, 0xA0, 0x00, 0x00, 0x00, 0x80, 0x3F)));

        // Re-encode is canonical: the one-byte word 0x20.
        Assert.Equal(
            Bytes(0x0D, 0x01, 0x20, 0x00, 0x00, 0x80, 0x3F),
            Encode(os => os.WriteArrayFp32(1, new[] { 1f })));
    }

    [Fact]
    public void SequenceEndWithNonZeroIdAccepted()
    {
        // §4.9: the id on a sequence-end header carries no information and MUST be
        // discarded -- the marker closes the innermost open sequence whatever the
        // id says. 0x87 0x01 is id 16, wire type 7; 0x87 0x00 is a non-minimal
        // spelling of id 0. Both are ordinary ends.
        var expected = new[] { "seq{:0", "u:1=3", "seq}" };
        Assert.Equal(expected, Decode(Bytes(0x06, 0x08, 0x03, 0x87, 0x01)));
        Assert.Equal(expected, Decode(Bytes(0x06, 0x08, 0x03, 0x87, 0x00)));
        Assert.Equal(expected, DecodeByteAtATime(Bytes(0x06, 0x08, 0x03, 0x87, 0x01)));

        // Re-encode is canonical: a bare 0x07 whatever the id on the wire said.
        Assert.Equal(
            Bytes(0x06, 0x08, 0x03, 0x07),
            Encode(os =>
            {
                os.WriteSequenceBeginLazy(0);
                os.WriteUnsigned(1, 3);
                os.WriteSequenceEnd();
            }));
    }

    [Fact]
    public void OversizedIdOnASequenceEndHeaderIsStillRejected()
    {
        // The other half of §4.9: "discarded is not unvalidated". The id is judged
        // on its VALUE at the point it is read, with no exception for wire type 7
        // (§6.2 admits none) -- 0x87 0x80 0x80 0x80 0x40 is (2^31 << 3) | 7, an id
        // one past ID_MAX. An implementation that validates the id only in the
        // branches that USE it passes every value-bearing case and misses this one.
        byte[] wire = Bytes(0x06, 0x87, 0x80, 0x80, 0x80, 0x40);

        var bulk = Assert.Throws<SofabException>(
            () => new IStream().Feed(wire, new RecordingVisitor()));
        Assert.Equal(SofabError.InvalidMessage, bulk.Error);

        var iss = new IStream();
        var visitor = new RecordingVisitor();
        var streamed = Assert.Throws<SofabException>(() =>
        {
            foreach (byte b in wire)
            {
                iss.Feed(new[] { b }, visitor);
            }
        });
        Assert.Equal(SofabError.InvalidMessage, streamed.Error);
    }
}
